# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://python:3.8.6-slim
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup PYTHONPATH
      run: |
        echo "PYTHONPATH=/home/runner/work/oauth-pyzure" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pipenv bandit 
        pipenv install
    - name: Code scanner - bandit
      run: |
        bandit -r ./oauth_pyzure
    - name: Test with pytest
      env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          PYTHON_PATH: ${{ secrets.PYTHONPATH }}
          APP_ID: ${{ secrets.APP_ID }}
          APP_ID_2: ${{ secrets.APP_ID_2 }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
      run: |
        cd tests
        pytest -v
